services:
  ina_zaoui_app:
    build: .
    container_name: ina_zaoui_app
    ports:
      - "8000:8000"
    depends_on:
      - ina_zaoui_postgres
    volumes:
      - ./:/var/www/symfony
  ina_zaoui_postgres:
    image: postgres:16-alpine
    container_name: ina_zaoui_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
  postgres_db:
    driver: local
